config/routes.rb
Rails.application.routes.draw do
  resources :cars
  root "cars#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
 validates :name, presence: true, length: { maximum: 70 }
validates :price, presence: true,
  numericality: { 
    only_integer: true,
    greater_than: 1
  }
validates :release_date, presence: true
validates :description, presence: true, length: { maximum: 2000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
def index
  @cars = Car.all
end
def new
  @car = Car.new
end

def create
  @car = Car.new(car_params)
  if @book.save
    redirect_to @car, notice: "新車を登録しました。"
  else
    render :new
  end
end

def show
  @car= Car.find(params[:id])
end
private

def car_params
  params.reqire(:car).permit(:name, :price, :release_date, :description)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with model: car, local: true do |form| %>
<%= render "shared/errors", obj: car %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %><br>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :release_date %><br>
    <%= form.date_field :release_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/cars/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">新車登録</h2>
  <%= render 'form', car: @car %>
</div>

app/views/cars/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <%= render "shared/notice" %>
  <h2><%= @car.name %></h2>
  <ul>
    <li><b>価格:</b><%= number_with_delimiter @car.price %>円</li>
    <li><b>発売日:</b><%= @car.publish_date %></li>
  </ul>
  <hr>
  <h4>商品の説明</h4>
  <%= simple_format @car.description %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "CarShop", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Car", new_car_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_notice.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>